"use client";

/**
 * Integrations Client
 *
 * Main integration page component
 * Features:
 * - API Keys management
 * - Integration snippets for Cloudflare & WordPress
 */

import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { toast } from "sonner";
import { Plus, Key, Copy, Check, AlertCircle } from "lucide-react";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Input } from "@/components/ui/input";
import { ApiKeyList } from "@/features/ai-crawlers/components/api-key-list";
import { ApiKeyCreateModal } from "@/features/ai-crawlers/components/api-key-create-modal";
import { IntegrationSnippets } from "@/features/ai-crawlers/components/integration-snippets";
import { createApiKeyAction, revokeApiKeyAction, clearPlaintextKeyAction } from "@/features/ai-crawlers/actions";

interface ApiKey {
  id: string;
  name: string;
  prefix: string;
  description: string | null;
  scopes: string[];
  createdAt: Date;
  lastUsedAt: Date | null;
  expiresAt: Date | null;
  plaintextKey: string | null;
}

interface IntegrationsClientProps {
  projectId: string;
  apiKeys: ApiKey[];
  isOwner: boolean;
}

export function IntegrationsClient({ projectId, apiKeys, isOwner }: IntegrationsClientProps) {
  const router = useRouter();
  const [isPending, startTransition] = useTransition();
  const [isCreateModalOpen, setIsCreateModalOpen] = useState(false);
  const [newlyCreatedKey, setNewlyCreatedKey] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);

  // Find auto-generated key with plaintext still available
  const autoGeneratedKey = apiKeys.find((k) => k.plaintextKey && k.name === "Default");

  const handleCopyAutoKey = async () => {
    if (!autoGeneratedKey?.plaintextKey) return;

    await navigator.clipboard.writeText(autoGeneratedKey.plaintextKey);
    setCopied(true);
    toast.success("API key copied to clipboard");

    // Clear the plaintext key after copying
    startTransition(async () => {
      await clearPlaintextKeyAction(projectId, autoGeneratedKey.id);
      router.refresh();
    });
  };

  const handleCreateKey = async (name: string, description?: string) => {
    startTransition(async () => {
      try {
        const result = await createApiKeyAction(projectId, name, description);

        if (result.success && result.plainKey) {
          setNewlyCreatedKey(result.plainKey);
          toast.success("API Key Created - Copy your key now. It won't be shown again.");
          router.refresh();
        } else {
          toast.error(result.error || "Failed to create API key");
        }
      } catch {
        toast.error("Failed to create API key");
      }
    });
  };

  const handleRevokeKey = async (keyId: string) => {
    startTransition(async () => {
      try {
        const result = await revokeApiKeyAction(projectId, keyId);

        if (result.success) {
          toast.success("API Key Revoked");
          router.refresh();
        } else {
          toast.error(result.error || "Failed to revoke API key");
        }
      } catch {
        toast.error("Failed to revoke API key");
      }
    });
  };

  const handleCloseModal = () => {
    setIsCreateModalOpen(false);
    setNewlyCreatedKey(null);
  };

  if (!isOwner) {
    return (
      <Card variant="bento" className="border-0 bg-transparent px-8 py-16">
        <CardContent className="px-0 flex flex-col items-center justify-center text-center space-y-8">
          <div className="flex h-16 w-16 items-center justify-center border border-dashed border-muted-foreground/40 bg-muted/5 text-muted-foreground">
            <Key className="h-8 w-8" />
          </div>
          <div className="space-y-3">
            <h3 className="text-xl font-bold uppercase tracking-tighter">
              Owner Access Required
            </h3>
            <p className="text-[10px] uppercase tracking-[0.2em] text-muted-foreground max-w-sm mx-auto leading-relaxed">
              Only project owners can manage integrations and API keys for security reasons.
            </p>
          </div>
        </CardContent>
      </Card>
    );
  }

  return (
    <div className="space-y-0">
      {/* Auto-generated Key Banner */}
      {autoGeneratedKey && (
        <Alert className="mx-8 mt-8 border-dashed border-primary/50 bg-primary/5">
          <AlertCircle className="h-4 w-4 text-primary" />
          <AlertTitle className="text-[10px] font-bold uppercase tracking-[0.2em]">
            Your Integration Key is Ready
          </AlertTitle>
          <AlertDescription className="mt-3 space-y-3">
            <p className="text-[10px] uppercase tracking-widest text-muted-foreground">
              Copy this key now. For security, it won&apos;t be shown again after you copy it.
            </p>
            <div className="flex gap-2">
              <Input
                readOnly
                value={autoGeneratedKey.plaintextKey || ""}
                className="font-mono text-xs h-9 border-dashed"
              />
              <Button
                onClick={handleCopyAutoKey}
                variant="outline"
                className="h-9 px-4 border-dashed gap-2"
                disabled={copied}
              >
                {copied ? (
                  <Check className="h-4 w-4 text-green-500" />
                ) : (
                  <Copy className="h-4 w-4" />
                )}
                {copied ? "Copied" : "Copy"}
              </Button>
            </div>
          </AlertDescription>
        </Alert>
      )}

      {/* API Keys Section */}
      <Card variant="bento" className="border-0 bg-transparent px-8 py-8">
        <CardHeader className="px-0 pb-8 flex flex-row items-center justify-between">
          <div>
            <CardTitle className="text-[10px] font-bold uppercase tracking-[0.2em] text-muted-foreground/80">
              API Keys
            </CardTitle>
            <CardDescription className="text-[9px] uppercase tracking-widest mt-1">
              Manage keys for Cloudflare & WordPress integrations
            </CardDescription>
          </div>
          <Button
            onClick={() => setIsCreateModalOpen(true)}
            className="uppercase text-[10px] font-bold tracking-widest px-6 h-9 gap-2"
            disabled={isPending}
          >
            <Plus className="h-4 w-4" />
            Create Key
          </Button>
        </CardHeader>
        <CardContent className="px-0">
          <ApiKeyList
            apiKeys={apiKeys}
            onRevoke={handleRevokeKey}
            isLoading={isPending}
          />
        </CardContent>
      </Card>

      {/* Integration Snippets Section */}
      <div className="border-t border-dashed border-border/80">
        <Card variant="bento" className="border-0 bg-transparent px-8 py-8">
          <CardHeader className="px-0 pb-8">
            <CardTitle className="text-[10px] font-bold uppercase tracking-[0.2em] text-muted-foreground/80">
              Integration Snippets
            </CardTitle>
            <CardDescription className="text-[9px] uppercase tracking-widest mt-1">
              Use Cloudflare Workers or WordPress to track AI crawlers and mentions
            </CardDescription>
          </CardHeader>
          <CardContent className="px-0">
            <IntegrationSnippets />
          </CardContent>
        </Card>
      </div>

      {/* Create Modal */}
      <ApiKeyCreateModal
        isOpen={isCreateModalOpen}
        onClose={handleCloseModal}
        onCreate={handleCreateKey}
        newlyCreatedKey={newlyCreatedKey}
        isLoading={isPending}
      />
    </div>
  );
}
